apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    
spec:
  selector:
    #Match the label of the POD
    matchLabels:
      env: production

  replicas: 3

  template:
      metadata:
        name: nginx-2
        labels:
          #The ReplicaSet match this label!
          env: production
    
      spec:
        containers:
         - name: nginx
           image: nginx

      
