apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
    
spec:
  selector:
    #Match the label of the POD
    matchLabels:
      env: production

  replicas: 3

  template:
      metadata:
        name: nginx-2
        labels:
          #The Deployment match this label!
          env: production
    
      spec:
        containers:
         - name: nginx
           image: nginx